name: pipeline

on:
  push:

jobs:
  pipeline:
    runs-on: ubuntu-latest
    env:
      PAGES_DOMAIN: thomasjamesgale.com
      BUILD_DIR: dist

    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: build ðŸ› ï¸
        uses: ./.github/actions/trunk
        with:
          cmd: trunk build --release

      - name: chown 
        run: sudo chown -R $(whoami) ${{ env.BUILD_DIR }}

      - name: configure the cname for github pages
        if: ${{ github.ref == 'refs/heads/main' }}
        run: echo ${{ env.PAGES_DOMAIN }} > ${{ env.BUILD_DIR }}/CNAME

      - name: disable jekyll
        if: ${{ github.ref == 'refs/heads/main' }}
        run: touch ${{ env.BUILD_DIR }}/.nojekyll

      - name: deploy github pages
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: crazy-max/ghaction-github-pages@v2.7.0
        with:
          build_dir: ${{ env.BUILD_DIR }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
